image: php:7.2-apache

stages:
  - test

# Get all required services to tests run.
services:
  - name: mariadb:10.3
    alias: db
  - name: redis:latest
    alias: cache

variables:
  MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  GET_SOURCES_ATTEMPTS: "2"

cache:
  paths:
  - vendor/

before_script:
  - bin/ci

php:
  stage: test
  script:
  - phpunit --coverage-text --colors=never