version: '3'

services:
  db:
    image: mariadb:10.3
    expose:
      - "3306"
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "127.0.0.1:8080:80"
    environment:
    - PMA_HOST=db

  cache:
    restart: always
    image: redis:4.0-alpine
    expose:
      - "6379"
    ports:
      - "127.0.0.1:6379:6379"

  http:
    build:
      context: var/docker/http
    command: "apache2-foreground"
    expose:
      - "80"
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - db
      - phpmyadmin
      - cache
    volumes:
      - ./:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT="/var/www/html/public"